Add type inference
InverseIntegral/js2wasm pull request #48
Opened 2018-11-23 15:27 UTC by InverseIntegral

2018-11-23 23:29 UTC, SeboCode requested changes

2018-11-23 23:29 UTC, SeboCode commented on src/generator/type_inference_visitor.ts
> +    private initializeTypes(tree: FunctionDeclaration, signature: FunctionSignature) {
Rename this method to `initializeParameterTypes`.

2018-11-23 23:29 UTC, SeboCode commented on src/generator/type_inference_visitor.ts
> +        if (isIdentifier(node.left)) {
This is the same logic as the one in `visitVariableDeclarator`. Therefore it should be combined.

2018-11-24 08:12 UTC, InverseIntegral commented on src/generator/type_inference_visitor.ts
> +        if (isIdentifier(node.left)) {
The combined method would be too generic. It would require at least three parameters which isn't better than what we have now.

2018-11-24 11:03 UTC, SeboCode approved these changes

2018-11-24 11:03 UTC, merged